### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by agnesedelzozzo** [szingaro/szingaro.github.io#3]
1. Nella pagina https://saltgz.github.io/education/2018/04/09/so-lab-cs/ , i pdf nella colonna a destra danno Error 404

2. Nella pagina https://saltgz.github.io/education/2018/07/04/ml-lab-mast/ , i due link n basso rimandano alla pagina stessa.

**Comment by saltgz** [comment]
Sarebbe più facile se fossero due ‘issues’ separate. Il punto 1. È stato corretto in [questo commit](
https://github.com/saltgz/saltgz.github.io/commit/d81947e855534aa4fd38da15ba41bfa0d5eb8fce).
